language: python
python:
- 3.8
services:
- docker
env:
- DOCKER_PYTHON_VERSION=3.8
install:
- docker build --build-arg PYTHON_VERSION="${DOCKER_PYTHON_VERSION}" -t "gitinsights-${DOCKER_PYTHON_VERSION}"
  .
script:
- export CODE_COV=`bash <(curl -s https://codecov.io/env)`
- docker run $CODE_COV "gitinsights-${DOCKER_PYTHON_VERSION}"
deploy:
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: jXICPcmrM2BuLWVsORRJn9AevFHjuw98egvAm/gVEynnIEMy7mDBz0YgyxuaLENipFmI5P9pl+E4ZSiVKSy8qhKX0qVSF9fYZMdkdJZJidncVf25j1Sm/kA/0eXBAfKzOF76z0V9z6D313EW1AZovm00fk/MU7WFrnTGM6YGrfWBiD5kzUh34lCFR4QKOUzKbPPawjnNBqrZzMNQ8PJXO0TyzWL7RMyMAlwZpqEOm8dVuKW70UeRcPECnd/CLCmpBaXNbkAE31obquQUH3Qb5+5oV6RPAthOkti+mlAKe2djYi/dWXkbRW/dofKwkWyZnV6O4mI6RlW+pl8iwqpKUGwIQiU2UX7NRr9LH5nQ8D9W1XpHDVgVQ3N5yNheeG3yXEvnMSN63VJo39T1pzz/HtYbFmxw7QqHDfaLTgp7eWHnYvNjBBkPE7dXL+IEwu+O0HLs9aqZR9zwjK4OoblbN2TFBJ9Z8uk6C1qDmjU/2I2Nup0JZ5xaLq+59TkI7ilWPQ3qVK4N3Kst6fptNIr3tOo/6ckEUruXlWn01A1ZT4jCMODuX20lxc9RaTvJ1scJT0pVdNiOjZE1Wp/dMYhuiiSKMNXhebeqFlHNFo/btP0OMWxjIVZamYORdNx26vmpVsIyP7mYp+DA0gdFJuO5BmSzdLeV6AZ5uAHQinHb+Xw=
  user: erikschlegel
deply-password:
  secure: Kwh9GV9mi19wSAaeP64MU955BHZDh820QXeYZ/W4kaguEg0uN19Lj43WhAU8D//673BGUiz33GTGpF5Xc7UP9XM26wmE55fAxKubN2GTR8ZaWPA73V5vneJHpKuHm+HSsDF35FmLUCEihcCIFV9MbQ2bpccT+s6eHzXL0mSGnxu7Gk1ecBeJ+sPuVtv66MQVbEBZK643rxCNjoUVIJYx8dOrgjjSnVIf5pKiDskHaq9R2gWQzX2uAIhOKnsPvvSUFb+mt0DlkwdL0K7ih+e663f4tPF99QOUPujreDk9L80VoPFNI2yZVv9PoC2cQ9Cr+pawTtgGmxVd5HMihNAAdQ+x1HCc4yPLj5VNPAQV01clQt2YC/vE12qYpF8Zy5MJSakq/3QDrlbdUeQpD6cxKbbErrri4bEt9hLTIs4lHn/Wmwzc9Ymi2fEu4yBfG5tDKUo+ETcTSwz+Js7BmpBBmreJAWX8vKuxAbcTxFzTalM0QOrn9+jEADPPp9G4J4aIysiIEa5uEy6WCHvhDjGF5xDBqWMJ0CHTMWtv4WyhtdbNDEzL/6P7DFMDfmmkz03WxcRrUhkfiG5oEoh53S0+Iw3ZMxMZXtxuwPjseW+duuC+TDD9kRl9I0jvn1znuPERnBOY71YnYyl6q/nTKOYatLb10VIGfwKduojXXd9pn0o=
