language: python
python:
- 3.8
services:
- docker
env:
- DOCKER_PYTHON_VERSION=3.8
install:
- docker build --build-arg PYTHON_VERSION="${DOCKER_PYTHON_VERSION}" -t "gitinsights-${DOCKER_PYTHON_VERSION}"
  .
script:
- export CODE_COV=`bash <(curl -s https://codecov.io/env)`
- docker run $CODE_COV "gitinsights-${DOCKER_PYTHON_VERSION}"
deploy:
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: 34m7CH6Beer5lBTFCbqcd13gDeNv4n85fMVRkCX6/Kh8VGj1dKVeKMjI3pz2pAB1FW6u1FyBUf/MFy1MjiOayWTvrJLVlQzU0Gx1vA+n69bLijj+4ku1n8xSSRkNBY8an8Fg/B+oVb15xNN3XP5AW6t0TFip7SMwLus1WB7ICkQezhLcicEyuP3efFWnLNtbIifiYLyW/Ejtq9x1IcJmlq9eAic3VgCINaI/NphaE+LIC+ot7MI6X/oQEajpo766cb1VjwjrKH4PXCBiAeUeokBnjI3VuXc6a78m/EDeNIge/dYz0OE2Q20ssG2DcqldAIwFUJ2+a3tKj5nt3dpGug6b4TXtMg9ckXTEnGNUkrRK9Xd1Sc6UPW8lcqelS96O3nUOL7s8yom/52T6lozGvTIY2oT+hlCJnqurx97Iphbp1AIlvH535OSgiOJeeEqW7TT5LbOTlxIpxna3uV9uWEZF2vuzisnbMbwkti+VCjELsGAXwb3CKT6K0ns/E9UN7vsMnXoE/6rziUHl+PXhWCAnX9wyqngef0hJEa0td0lroBy/At3ML0yQ/NzCWn7Fm/lP8OuPTWTDDiKGe0cZb0PpC2doV41z/t3hziEj9uwwLSiReISu9cYQSVq9wDYXHReXACPM8SGolCUNA9avWqQdSDqUOYr3jOm6kuSDBDU=
  user: erikschlegel
deply-password:
  secure: Kwh9GV9mi19wSAaeP64MU955BHZDh820QXeYZ/W4kaguEg0uN19Lj43WhAU8D//673BGUiz33GTGpF5Xc7UP9XM26wmE55fAxKubN2GTR8ZaWPA73V5vneJHpKuHm+HSsDF35FmLUCEihcCIFV9MbQ2bpccT+s6eHzXL0mSGnxu7Gk1ecBeJ+sPuVtv66MQVbEBZK643rxCNjoUVIJYx8dOrgjjSnVIf5pKiDskHaq9R2gWQzX2uAIhOKnsPvvSUFb+mt0DlkwdL0K7ih+e663f4tPF99QOUPujreDk9L80VoPFNI2yZVv9PoC2cQ9Cr+pawTtgGmxVd5HMihNAAdQ+x1HCc4yPLj5VNPAQV01clQt2YC/vE12qYpF8Zy5MJSakq/3QDrlbdUeQpD6cxKbbErrri4bEt9hLTIs4lHn/Wmwzc9Ymi2fEu4yBfG5tDKUo+ETcTSwz+Js7BmpBBmreJAWX8vKuxAbcTxFzTalM0QOrn9+jEADPPp9G4J4aIysiIEa5uEy6WCHvhDjGF5xDBqWMJ0CHTMWtv4WyhtdbNDEzL/6P7DFMDfmmkz03WxcRrUhkfiG5oEoh53S0+Iw3ZMxMZXtxuwPjseW+duuC+TDD9kRl9I0jvn1znuPERnBOY71YnYyl6q/nTKOYatLb10VIGfwKduojXXd9pn0o=
