language: python
python:
- 3.8
services:
- docker
env:
- DOCKER_PYTHON_VERSION=3.8
install:
- docker build --build-arg PYTHON_VERSION="${DOCKER_PYTHON_VERSION}" -t "gitinsights-${DOCKER_PYTHON_VERSION}"
  .
script:
- export CODE_COV=`bash <(curl -s https://codecov.io/env)`
- docker run $CODE_COV "gitinsights-${DOCKER_PYTHON_VERSION}"
deploy:
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: Ig8ZRZa5NGDdrd05DBFFC80x6zV4v1zrw2VrRtjaSBWtkc2kvBBmsDCykSvbjGGkuPq42+5kwFpna0AZI5vfVC1tvZ6TLNOwbVD0dysb7aV5F954P4mvi9ZTaIlYlPRrsCkYG/Ho3ejfKgTAsUvl1PJ7ctQHlYkI1Hqxl5V5sx7zugC2CNL6Gnv6pTBQi6FtLseNal6hU1H+7DwUC1HBTVY9+MqNolhJrf3KIu5EDnmAdthEaOLi5uI1qgsk3BKrgu5wRBecpuc1gy/G4wsbyoTR5ke86T5+KW7cEpx34vzPa0X0ZN12RCP7j5x81bYNZPw8cqjm4DY/5OynKzhVnInpUasSYZnIG9u0vkWLSnUcyjXsyniy4/zFhTXe6gOaDmV8Hr1lIC8pDlA2uBZaCwH7ywpvbToNpKI9C6jt5uIEcLLXmTg+OY632GMD/kEfXsi+d08/R3aOOmP2M+cgGBpZIR9GLiYX9zIPGtAqLIzX+y42ab8nB5Cn4GMTzn+QouvpYTUn2Lsk2HdFc4sGB61XWJIvbwYJLXq8f+x4tu4VGW2pX8WVJIMwx9+L74ja6Zat+ZlEa55Rltm0qTCD7CxdVZLzgGBN7Sc3JVlC4HtVAvg/sZdndICgBC6d+Azr3g/X3njaWwWjloB/1aiXB/5JfVvl1L+5gOmSL7Uz2WU=
  user: erikschlegel
deply-password:
  secure: Kwh9GV9mi19wSAaeP64MU955BHZDh820QXeYZ/W4kaguEg0uN19Lj43WhAU8D//673BGUiz33GTGpF5Xc7UP9XM26wmE55fAxKubN2GTR8ZaWPA73V5vneJHpKuHm+HSsDF35FmLUCEihcCIFV9MbQ2bpccT+s6eHzXL0mSGnxu7Gk1ecBeJ+sPuVtv66MQVbEBZK643rxCNjoUVIJYx8dOrgjjSnVIf5pKiDskHaq9R2gWQzX2uAIhOKnsPvvSUFb+mt0DlkwdL0K7ih+e663f4tPF99QOUPujreDk9L80VoPFNI2yZVv9PoC2cQ9Cr+pawTtgGmxVd5HMihNAAdQ+x1HCc4yPLj5VNPAQV01clQt2YC/vE12qYpF8Zy5MJSakq/3QDrlbdUeQpD6cxKbbErrri4bEt9hLTIs4lHn/Wmwzc9Ymi2fEu4yBfG5tDKUo+ETcTSwz+Js7BmpBBmreJAWX8vKuxAbcTxFzTalM0QOrn9+jEADPPp9G4J4aIysiIEa5uEy6WCHvhDjGF5xDBqWMJ0CHTMWtv4WyhtdbNDEzL/6P7DFMDfmmkz03WxcRrUhkfiG5oEoh53S0+Iw3ZMxMZXtxuwPjseW+duuC+TDD9kRl9I0jvn1znuPERnBOY71YnYyl6q/nTKOYatLb10VIGfwKduojXXd9pn0o=
