language: python
python:
- 3.8
services:
- docker
env:
- DOCKER_PYTHON_VERSION=3.8
install:
- docker build --build-arg PYTHON_VERSION="${DOCKER_PYTHON_VERSION}" -t "gitinsights-${DOCKER_PYTHON_VERSION}"
  .
script:
- export CODE_COV=`bash <(curl -s https://codecov.io/env)`
- docker run $CODE_COV "gitinsights-${DOCKER_PYTHON_VERSION}"
deploy:
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: hegflpb0xV5jNo+e9lOiy1cRleL8TccCdlvDNH0J6JNtsLcFdumvWa/qntU6LDaRLjwUGts/r7ZCNk/kDlskbo36SbQqsHfTWh9OcxZTnlx5zURs91H6/+joT5tHp3WPG6xDYjCBzS9f6bDekhh7YzHmwyGiy7E+BEFDmxLiSc9RE53n33YkiLdHkIT6wtcIDjP3M1gsqKCpHBZDSGlqz/bKjkj0bxEA51WsdElA5ysi9YhQXUJRs/O3byzaHJ526M0wLJwWikUk2ZIjyBj1soz+oOQYsB4SLv2HP+yl5KE6cqgvxcBvXO3Q/HIUUP0lHakSL6jGGNuE8OWmT6vUcDPgWJpQQhdvJONPdLiTJ4RPbvPS11KwXwC4aXoti0R5ppKoFXpJCFoQmckF+9honpIsa9oW5UTLdsI/hd/EIYDqmVyTFySR8cN/qROsfMTF+tk//ifP2ob7kqgOG9neCmCtDdzlZO86cKJss2TxIJpny1S28XAcFbBgv5+Tf/sl4E55kTmTtivp5PAzP1v5FAmkeCWiJ+W6b0gx1ZXrNVs6rOwFTEoRdbD6HbfHfz23fNXp+cX/vDX2/td700ck73V91R+3pK5d0AkhSPMN7UzOFQ5u/zmrkc+2BToLs1ETwckIRrGf1yg39JloL6/V4aZVE0T8GKXeT4JGbW/C69E=
  user: erikschlegel
deply-password:
  secure: Kwh9GV9mi19wSAaeP64MU955BHZDh820QXeYZ/W4kaguEg0uN19Lj43WhAU8D//673BGUiz33GTGpF5Xc7UP9XM26wmE55fAxKubN2GTR8ZaWPA73V5vneJHpKuHm+HSsDF35FmLUCEihcCIFV9MbQ2bpccT+s6eHzXL0mSGnxu7Gk1ecBeJ+sPuVtv66MQVbEBZK643rxCNjoUVIJYx8dOrgjjSnVIf5pKiDskHaq9R2gWQzX2uAIhOKnsPvvSUFb+mt0DlkwdL0K7ih+e663f4tPF99QOUPujreDk9L80VoPFNI2yZVv9PoC2cQ9Cr+pawTtgGmxVd5HMihNAAdQ+x1HCc4yPLj5VNPAQV01clQt2YC/vE12qYpF8Zy5MJSakq/3QDrlbdUeQpD6cxKbbErrri4bEt9hLTIs4lHn/Wmwzc9Ymi2fEu4yBfG5tDKUo+ETcTSwz+Js7BmpBBmreJAWX8vKuxAbcTxFzTalM0QOrn9+jEADPPp9G4J4aIysiIEa5uEy6WCHvhDjGF5xDBqWMJ0CHTMWtv4WyhtdbNDEzL/6P7DFMDfmmkz03WxcRrUhkfiG5oEoh53S0+Iw3ZMxMZXtxuwPjseW+duuC+TDD9kRl9I0jvn1znuPERnBOY71YnYyl6q/nTKOYatLb10VIGfwKduojXXd9pn0o=
